# Generated by Django 5.0.6 on 2024-06-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome do produto"),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=200, verbose_name="Descrição do produto"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor do produto"
                    ),
                ),
                (
                    "disponivel",
                    models.CharField(
                        choices=[("S", "SIM"), ("N", "NAO")],
                        max_length=1,
                        verbose_name="Disponibilidade",
                    ),
                ),
            ],
        ),
    ]
