# Generated by Django 5.0.6 on 2024-06-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produtos",
            name="quantidade",
            field=models.BigIntegerField(
                default=1, verbose_name="quantidade de produtos"
            ),
            preserve_default=False,
        ),
    ]
